export const dummy = {
	dates: {
		maximum: '2024-01-31',
		minimum: '2023-12-20',
	},
	page: 1,
	results: [
		{
			adult: false,
			backdrop_path: '/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg',
			genre_ids: [28, 12, 14],
			id: 572802,
			original_language: 'en',
			original_title: 'Aquaman and the Lost Kingdom',
			overview:
				'아틀란티스 왕국을 이끌 왕의 자리에 오른 아쿠아맨. 그 앞에 블랙 만타가 세상을 뒤흔들 강력한 지배 아이템 블랙 트라이던트를 손에 넣게 된다. 그동안 겪지 못 했던 최악의 위협 속 아쿠아맨은 블랙 만타와 손을 잡았던 이복 동생 옴 없이는 절대적 힘이 부족한 상황. 바다를 지배할 슈퍼 히어로가 세상의 판도를 바꾼다!',
			popularity: 5876.8,
			poster_path: '/eDps1ZhI8IOlbEC7nFg6eTk4jnb.jpg',
			release_date: '2023-12-20',
			title: '아쿠아맨과 로스트 킹덤',
			video: false,
			vote_average: 6.909,
			vote_count: 981,
		},
		{
			adult: false,
			backdrop_path: '/r1eCvALF6fN7anVYL8Zn7PaceD1.jpg',
			genre_ids: [35, 10751, 14],
			id: 787699,
			original_language: 'en',
			original_title: 'Wonka',
			overview:
				'마법사이자 초콜릿 메이커 ‘윌리 웡카’의 꿈은 디저트의 성지, ‘달콤 백화점’에 자신만의 초콜릿 가게를 여는 것. 가진 것이라고는 낡은 모자 가득한 꿈과 단돈 12소베른 뿐이지만 특별한 마법의 초콜릿으로 사람들을 사로잡을 자신이 있다. 하지만 먹을 것도, 잠잘 곳도, 의지할 사람도 없는 상황 속에서 낡은 여인숙에 머물게 된 ‘웡카’는 ‘스크러빗 부인’과 ‘블리처’의 계략에 빠져 눈더미처럼 불어난 숙박비로 인해 순식간에 빚더미에 오른다. 게다가 밤마다 초콜릿을 훔쳐가는 작은 도둑 ‘움파 룸파’의 등장과 ‘달콤 백화점’을 독점한 초콜릿 카르텔의 강력한 견제까지. 세계 최고의 초콜릿 메이커가 되는 길은 험난하기만 한데…',
			popularity: 3324.613,
			poster_path: '/g5mGMbiZLvgEf628D60GQrPHFJC.jpg',
			release_date: '2024-01-31',
			title: '웡카',
			video: false,
			vote_average: 7.208,
			vote_count: 1538,
		},
		{
			adult: false,
			backdrop_path: '/meyhnvssZOPPjud4F1CjOb4snET.jpg',
			genre_ids: [16, 12, 35, 10751, 28],
			id: 940551,
			original_language: 'en',
			original_title: 'Migration',
			overview:
				'가족을 과잉보호하는 아빠 ‘맥’ 때문에 평생을 작은 연못에서 안전하게 살아온 말러드 가족. 하지만 호기심 가득한 남매 ‘댁스’와 ‘그웬’을 위해 새로운 세상을 모험하고 싶은 엄마 ‘팸’의 설득으로 가족들은 항상 꿈꿔온 자메이카로 생애 첫 가족 모험을 떠나기로 한다! 설렘 넘치는 시작과 달리 태풍을 만나 길을 잃고, 낯선 친구들을 만나고, 위험 가득한 뉴욕에 불시착하게 된다. 인생 처음으로 모든 계획이 틀어지고 위기에 빠진 말러드 가족은 서툴지만 서로를 의지하며 모험을 계속한다. 새로운 세상, 함께라면 두려울 것 없어!',
			popularity: 2295.419,
			poster_path: '/2xE3NI6zElWhwN9WJ92fqbZKmzZ.jpg',
			release_date: '2024-01-10',
			title: '인투 더 월드',
			video: false,
			vote_average: 7.7,
			vote_count: 295,
		},
		{
			adult: false,
			backdrop_path: '/ehumsuIBbgAe1hg343oszCLrAfI.jpg',
			genre_ids: [16, 10751, 14, 12],
			id: 1022796,
			original_language: 'en',
			original_title: 'Wish',
			overview:
				'마음 속 깊이 ‘소원’을 품고 있는 모두를 위한 디즈니의 마법! 용감한 ‘아샤’와 신비로운 ‘별’의 특별한 여정 & 소원과 얽힌 비밀스러운 힘을 지닌 ‘매그니피코 왕’의 숨겨진 스토리까지! 2024년 1월, 믿고 듣는 디즈니표 명품 OST와 함께 아름다운 로사스 왕국에서 펼쳐지는 가슴 벅찬 이야기!',
			popularity: 1647.057,
			poster_path: '/lnOgP8Fl2dQ73d4Qu24O2zcKFFS.jpg',
			release_date: '2024-01-03',
			title: '위시',
			video: false,
			vote_average: 6.481,
			vote_count: 454,
		},
		{
			adult: false,
			backdrop_path: '/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg',
			genre_ids: [16, 10751, 10402, 14, 35],
			id: 901362,
			original_language: 'en',
			original_title: 'Trolls Band Together',
			overview:
				'전 세계 모든 트롤을 열광케 했던 최고의 아이돌 그룹 ‘브로존’. 역대급 무대 실수와 형제 간의 불화로 결국 해체한 뒤, 모두에게 잊혀 간다. 그러던 어느 날, ‘브로존’의 황금막내 ‘브랜치’는 메인보컬 ‘플로이드’가 슈퍼스타 ‘벨벳’과 ‘비니어’에게 잡혀 재능을 빼앗기고 있다는 소식을 듣는다. 그를 구하기 위해서는 흩어져 있는 ‘브로존’을 재결합하고 완벽한 화음을 되찾아야 하는데… 12월, 가장 짜릿한 컴백 무대의 시작!',
			popularity: 359.962,
			poster_path: '/qzgEPduJyQ6RkgMdn4nbjdKUYJM.jpg',
			release_date: '2023-12-20',
			title: '트롤: 밴드 투게더',
			video: false,
			vote_average: 7.225,
			vote_count: 580,
		},
		{
			adult: false,
			backdrop_path: '/riuTxOEKQ9lfvSan2vwaOPipwtr.jpg',
			genre_ids: [35, 18],
			id: 621587,
			original_language: 'en',
			original_title: 'Next Goal Wins',
			overview:
				'인성 논란으로 퇴출 위기에 놓인 축구 감독 토머스 론겐은 31: 0 이라는 기록적인 패배로 창설 이후 단 한 골도 넣지 못한 FIFA 랭킹 최하위 아메리칸 사모아 국가 대표팀의 감독을 어쩔 수 없이 맡게 된다. 부임 첫 날부터 축구의 기본 규칙도 모르지만 독특한 개성과 능력을 지닌 선수들과 끊임없이 충돌하고… 승률 제로, 단합 제로, 용기 제로 모든 것이 부족한 선수들과 론겐은 고군 분투하게 된다. 그들의 목표는 승리도, 우승도 아닌 오직 한 골! 마침내 코 앞으로 다가온 월드컵 예선전, 그들은 그토록 바라던 단 한 골을 넣을 수 있을까?',
			popularity: 325.89,
			poster_path: '/wxFHtgrFUx85IbVb1GiKPSwxG95.jpg',
			release_date: '2024-01-24',
			title: '넥스트 골 윈즈',
			video: false,
			vote_average: 6.496,
			vote_count: 140,
		},
		{
			adult: false,
			backdrop_path: '/fGe1ej335XbqN1j9teoDpofpbLX.jpg',
			genre_ids: [18, 9648],
			id: 915935,
			original_language: 'fr',
			original_title: "Anatomie d'une chute",
			overview:
				'산드라와 사뮤엘은 시각 장애가 있는 아들 다니엘과 함께 프랑스 알프스의 외딴 산장에서 살고 있다. 갑작스러운 사뮤엘의 죽음 이후, 그의 죽음이 자살인지 혹은 범죄에 연루된 것인지를 밝히는 조사는 점차 미궁으로 빠진다.',
			popularity: 224.159,
			poster_path: '/zIxTPoS6zd3txeLP5FUdo3CSfbo.jpg',
			release_date: '2024-01-31',
			title: '추락의 해부',
			video: false,
			vote_average: 7.762,
			vote_count: 764,
		},
		{
			adult: false,
			backdrop_path: '/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg',
			genre_ids: [28, 53, 80],
			id: 762430,
			original_language: 'en',
			original_title: 'Retribution',
			overview:
				'대규모 자금을 운용하는 펀드 매니저 ‘매트’(리암 니슨)에게 걸려온 한 통의 미확인 발신자 전화!  그의 요구는 2억 8천만 유로를 송금할 것, 전화를 끊거나 차를 멈추지 말 것!',
			popularity: 173.249,
			poster_path: '/jJNgvme2a51MRCJoE7dL4Vpzv8Z.jpg',
			release_date: '2024-01-24',
			title: '레트리뷰션',
			video: false,
			vote_average: 6.827,
			vote_count: 860,
		},
		{
			adult: false,
			backdrop_path: '/nvW0QfRJ7ga9TK8DKwBfAPA8ywP.jpg',
			genre_ids: [28, 18, 80],
			id: 944401,
			original_language: 'en',
			original_title: 'Dogman',
			overview:
				'뉴저지의 한 도심, 핑크 드레스에 짙은 화장을 한 남자가 수백 마리의 개와 함께 긴급 체포된다. 아무런 진술도 하지 않던 그는 정신과 의사에게 15년간의 이야기를 털어놓기 시작하는데... 신마저 외면했지만 개를 통해 구원받은 한 남자의 처절하고 아름다운 이야기가 펼쳐진다!',
			popularity: 161.13,
			poster_path: '/ggEVrwwk68QBcygzvzCV0fvRLEY.jpg',
			release_date: '2024-01-24',
			title: '도그맨',
			video: false,
			vote_average: 7.398,
			vote_count: 220,
		},
		{
			adult: false,
			backdrop_path: '/oQMcTqUkz1LIQceyjyiA4UO9UgM.jpg',
			genre_ids: [35, 18, 10749],
			id: 986280,
			original_language: 'fi',
			original_title: 'Kuolleet lehdet',
			overview:
				'2024년, 헬싱키의 외로운 두 영혼 안사와 홀라파는 어느 날 우연히 만나 눈길을 주고받는다. “그럼 또 만날까요? 근데 이름도 모르네요” “다음에 알려줄게요” 서로의 이름도, 주소도 알지 못한 채 유일하게 받아 적은 전화번호마저 잃어버린다. 운명이 이들을 갈라놓으려 할 때 두 사람은 다시 만날 수 있을까?',
			popularity: 55.049,
			poster_path: '/3D3w06xQtFcFEFuYuv9D6m93fJM.jpg',
			release_date: '2023-12-20',
			title: '사랑은 낙엽을 타고',
			video: false,
			vote_average: 7.258,
			vote_count: 232,
		},
		{
			adult: false,
			backdrop_path: '/kZbTOcTrEGyroQMWQSGIRlNSkwP.jpg',
			genre_ids: [878, 28, 14, 12],
			id: 626412,
			original_language: 'ko',
			original_title: '외계+인 2부',
			overview:
				'인간의 뇌 속에 갇혀 있는 외계인 포로들의 탈출을 막으려다 먼 과거에 갇혀버린 이안과 썬더는 시간을 관통하는 문을 열 수 있는 신검을 얻게 된다. 한편, 이안의 탈출을 도왔던 무륵은 자신의 몸에 이상한 존재가 있다는 것을 느끼자 혼란에 빠진다. 무륵의 몸에 숨어있는 외계인으로 의심되는 존재가 이안과 무륵을 추격하기 시작하고, 이안은 미래로 돌아가 외계인과 맞서 하바의 폭발을 막아야만 하는데.  마침내 시간의 문이 열리고 무륵, 이안, 썬더의 비밀이 드러나기 시작한다!',
			popularity: 65.06,
			poster_path: '/hBxVes0oK7uoNwAQ2meJ2LVthPI.jpg',
			release_date: '2024-01-10',
			title: '외계+인 2부',
			video: false,
			vote_average: 7,
			vote_count: 27,
		},
		{
			adult: false,
			backdrop_path: '/bQTfSXQrcVwXJ5TvNzbd3ioMnnM.jpg',
			genre_ids: [9648, 53, 28, 18],
			id: 862552,
			original_language: 'en',
			original_title: 'The Ritual Killer',
			overview:
				'강력계 형사 루카스 보이드는 딸과 아내의 죽음으로 괴로워하며 하루하루를 살아간다. 그러던 중 매우 기괴하고 잔인한 수법의 살인사건이 발생한다. 사건현장을 둘러보고 평범한 살인사건이 아니라고 판단한 루카스는 아프리카 문화의 권위자로 꼽히는 맥클스 교수를 찾아가 도움을 청한다. 루카스는 범인이 고객의 의뢰를 받고 무티라는 의식을 거행하기 위해 피해자들을 제물로 사용한다는 사실을 알아내고 맥클스 교수의 도움으로 남아공 출신의 흑주술사 랜도쿠를 뒤쫓는다. 한편 거대 다국적 기업의 대표인 파너의 의뢰를 받고 일하는 랜도쿠는 또 다른 범행을 꾸미는데... 과연 루카스 형사는 잔인한 살인마이자 흑주술사인 랜도쿠를 막을 수 있을까?',
			popularity: 64.623,
			poster_path: '/ivfflZulJY4qtHcsAZ7P94ygJ15.jpg',
			release_date: '2024-01-17',
			title: '무티: 주술살인',
			video: false,
			vote_average: 6.1,
			vote_count: 225,
		},
		{
			adult: false,
			backdrop_path: '/9ZlGiEKmcYrrxmiQEJDhjeT2kEW.jpg',
			genre_ids: [28, 12, 10752],
			id: 1061181,
			original_language: 'ja',
			original_title: 'キングダム 運命の炎',
			overview:
				'천하대장군을 꿈꾸는 소년 ‘신’, 조나라가 10만 대군을 이끌고 진나라에 침공을 강행하자 보병대로 전쟁에 출전한다. 진나라가 요충지까지 함락당하며 멸망의 위기에 놓인 그때, ‘신’은 전설의 천하대장군 ‘왕기’에게 100인 부대의 대장으로 임명되어 특수한 임무를 하달받는다. 단 100명의 비신대를 이끌고 적진에 침투하라! ‘신’과 동료들은 목숨을 건 운명의 전투를 시작하는데…!',
			popularity: 60.845,
			poster_path: '/vUSJ6NPA7ZigGi9l5sGzKRAJt8g.jpg',
			release_date: '2024-01-17',
			title: '킹덤3: 운명의 불꽃',
			video: false,
			vote_average: 7.625,
			vote_count: 92,
		},
		{
			adult: false,
			backdrop_path: '/2C3CdVzINUm5Cm1lrbT2uiRstwX.jpg',
			genre_ids: [28, 14, 10752],
			id: 856289,
			original_language: 'zh',
			original_title: '封神第一部：朝歌风云',
			overview:
				'반란군과의 전쟁에서 승리한 왕자 은수. 절세미인 달기와 부왕을 죽이고 왕좌에 오른다. 천륜을 저버린 만행과 폭정에 하늘이 노하고 원시천존은 천벌이 내려진 인간들을 구할 ‘봉신방’을 강지아에게 주어 인간계로 보낸다. 사대백후를 제거한 은수에게 마계가 동참하고 마침내 신계, 인간계, 마계의 전쟁이 불타오르는데… 장대한 판타지 액션 대서사시를 만난다',
			popularity: 47.65,
			poster_path: '/m2RkBs6hdaqOsDWeua7CJmPxP3V.jpg',
			release_date: '2024-01-24',
			title: '봉신연의: 조가풍운',
			video: false,
			vote_average: 7.3,
			vote_count: 119,
		},
		{
			adult: false,
			backdrop_path: '/qXD5vfFe1blOXJbOHXlU5CYJMQB.jpg',
			genre_ids: [16, 28, 10751, 878],
			id: 16577,
			original_language: 'en',
			original_title: 'Astro Boy',
			overview:
				"과학의 도시 메트로 시티. 최고의 과학자인'텐마 박사'는 로봇 시험 가동 중 자신의 실수로 아들'토비'를 잃고 괴로워한다. 그는'토비'의 DNA와 하이 테크놀로지가 결합된 최고의 로봇을 탄생시키는데...",
			popularity: 40.212,
			poster_path: '/92MAWCJLYzzHFvzUlJBt1qmaiZd.jpg',
			release_date: '2024-01-31',
			title: '아톰 새로운 시작',
			video: false,
			vote_average: 6.291,
			vote_count: 1442,
		},
		{
			adult: false,
			backdrop_path: '/hb0BeFvZNx2zLGWwuwENOIVeK1U.jpg',
			genre_ids: [35, 18, 36],
			id: 792293,
			original_language: 'en',
			original_title: 'Dumb Money',
			overview:
				'“주식 시장에서 이렇게 황당한 일은 처음 봐요!” “상승세가 멈추질 않는데요?” 월 스트리트를 제대로 물 먹인 개미들의 짜릿한 떡상 실화 스토리가 시작된다!',
			popularity: 40.391,
			poster_path: '/hSJl0U8Wi1YVORKI0hIbiXt1xSL.jpg',
			release_date: '2024-01-17',
			title: '덤 머니',
			video: false,
			vote_average: 6.719,
			vote_count: 242,
		},
		{
			adult: false,
			backdrop_path: '/xkOax3HOpxhdz2hnMEBvSkWEmnM.jpg',
			genre_ids: [28, 80, 53],
			id: 829799,
			original_language: 'en',
			original_title: 'Paradise City',
			overview:
				'현상금 사냥꾼 ‘이언 스완’은 ‘마약 밀매 조직의 두목을 쫓다 살해당하고, 그의 아들 라이언은 아버지의 마지막 메시지를 듣고 살인범을 찾으러 하와이에 온다. 라이언은 아버지의 옛 동료인 로비를 찾아가 도움을 청하고, 이언의 사건을 수사하던 경찰 ‘사바나’도 두 사람의 추적에 합류한다.한편 하와이의 권력자인 ‘버클리’는 지역을 장악하기 위해 마우이 주지사 자리에 꼭두각시 현지인 후보를 당선시키기 위해 노력하고, 자신의 일에 방해가 되는 로비를 납치하는데…',
			popularity: 38.082,
			poster_path: '/41XYtjIZxUd65Epw00FQnduFeyQ.jpg',
			release_date: '2024-01-18',
			title: '파라다이스 시티',
			video: false,
			vote_average: 5.692,
			vote_count: 125,
		},
		{
			adult: false,
			backdrop_path: '/AfyuI3glMCBDFmNPj9PY6DwbgGp.jpg',
			genre_ids: [16, 878, 28, 18],
			id: 18491,
			original_language: 'ja',
			original_title: '新世紀エヴァンゲリオン劇場版 Air／まごころを、君に',
			overview:
				'‘카오루’의 죽음 이후 공황 상태에 빠진 ‘신지’. 한편, 네르프 총사령관 ‘겐도’는 ‘서드 임팩트’ 즉, ‘인류보완계획’을 놓고 ‘제레’와 갈등을 벌인다. 이에 ‘제레’는 양산형 에바를 투입해 네르프 본부와 에바 파일럿들을 향해 총공격을 감행하고 맹공에 혼수 상태였던 ‘아스카’까지 완전히 폭주한다. ‘신지’는 ‘미사토’의 도움으로 겨우 초호기에 오르지만, 인류의 운명을 결정해야 하는 상황에 한계에 부딪히게 되는데…',
			popularity: 31.885,
			poster_path: '/rS97sHvlsUAp8F6tkC78YjRU8wl.jpg',
			release_date: '2024-01-17',
			title: '엔드 오브 에반게리온',
			video: false,
			vote_average: 8.3,
			vote_count: 1444,
		},
		{
			adult: false,
			backdrop_path: '/t4xUXeAFAMw0gtMNQ4y3R60KiNr.jpg',
			genre_ids: [16, 35],
			id: 1059572,
			original_language: 'ja',
			original_title:
				'しん！クレヨンしんちゃんTHE MOVIE 超能力大決戦 ～とべとべ手巻き寿司～',
			overview:
				'어느 날, 우주에서 날아온 검은 빛과 하얀 빛이 떡잎마을을 향해 떨어진다. 평소처럼 저녁밥을 손꼽아 기다리던 짱구는 하얀 빛에 정통으로 맞게 되고 그러자 온몸에 넘치는 신비한 힘! 힘에 몸을 맡긴 채 엉덩이에 의식을 집중하자 장난감들이 붕붕 떠오른다.  한편, 검은 빛을 통해 초능력을 손에 넣은 또 다른 남자는 이 세상의 파멸을 바라며 폭주하기 시작하는데, 위기에 처한 세상을 구하기 위한 유일한 희망이 바로 짱구...!?',
			popularity: 28.119,
			poster_path: '/39nnJB6453mDocXqy2RGc2zZ3wY.jpg',
			release_date: '2023-12-22',
			title: '신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~',
			video: false,
			vote_average: 8,
			vote_count: 2,
		},
		{
			adult: false,
			backdrop_path: '/oeBom7DLr85lixEkWOGmhCPEfuY.jpg',
			genre_ids: [80, 18, 53],
			id: 842942,
			original_language: 'en',
			original_title: 'Bandit',
			overview:
				'1985년, 미시간 교도소에서 탈옥해 캐나다로 건너간 한 남자. 노숙자에게 22달러에 신분증을 구매해 ‘로버트 화이트만’으로 새로운 삶을 시작하고, 돈을 마련하기 위해 은행 강도에 나선다. 변장과 은행털이에 남다른 재능을 발견한 그는 비행기를 타고 캐나다 전역을 누비며 무려 59번의 강도 행각을 벌이는데…',
			popularity: 25.421,
			poster_path: '/a8v0tN3D0sFwBH2YVuQRpzhUE0i.jpg',
			release_date: '2023-12-28',
			title: '밴디트',
			video: false,
			vote_average: 6.178,
			vote_count: 269,
		},
	],
	total_pages: 4,
	total_results: 63,
};
